add_newline = true
scan_timeout = 10

[username]
disabled = false
show_always = false

[hostname]
ssh_only = true
disabled = false

[battery]
disabled = true

[character]
use_symbol_for_status = true

[cmd_duration]
prefix = ""

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 0

[git_commit]
disabled = false
commit_hash_length = 7
prefix = ""
suffix = " "

[git_state]
progress_divider = "/"

[git_status]
disabled = true

[python]
pyenv_version_name = true
