add_newline = true
# scan_timeout = 10
# command_timeout = 4000

[username]
disabled = false
show_always = false

[hostname]
disabled = false
ssh_only = true

[battery]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
format = "[$duration]($style) "

[directory]
truncation_length = 2
fish_style_pwd_dir_length = 0

[git_status]
disabled = true

# [git_metrics]
# disabled = false

[python]
pyenv_version_name = true
